plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pattiz.wintabkeyboard'
    compileSdk 34

    defaultConfig {
        applicationId "com.pattiz.wintabkeyboard"
        minSdk 21
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
