plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pattiz.wintabkeyboard'
    compileSdk 34

    signingConfigs {
        wintabDev {
            storeFile file("../wintab-dev-key.jks")
            storePassword "wintabdev2026"
            keyAlias "wintabdev"
            keyPassword "wintabdev2026"
        }
    }

    defaultConfig {
        applicationId "com.pattiz.wintabkeyboard"
        minSdk 21
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.wintabDev
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.wintabDev
        }
    }
}
